### ISSUE TITLE
Branch names should be predictable and collisions should create new commits

### ISSUE THREAD

**Issue by AlbertoFemenias** [prefapp/action-state-repo-update-image#89]
### Motivation

Right now the action creates one branch for each pr with a name like this:
```js
automated/update-image-${tenant}-${app}-${env}-${service}
```

We should get rid of that timestamp and if there is a collision (there is already a branch like that), it should try to add a new commit updating the image instead of opening various pr for the same change.

We want also to simplify PR names with something like "Service image update" and then add the deployment coordinates to as PR labels

tenant
environment
application
service_name

We need to check, before creating a new PR, that a previous PR deployment exists, and, in that case, update that PR instead of opening a new one, to avoid confusion for the platform team with the manual-approval PRs.

To make the action and PRs idempotent, we remove the feature of updating more than one service per PR.

### Acceptance criteria
- [ ] The action makes a commit if the branch already exists
- [ ] If the branch exists but the PR is not open for that branch, open it
- [ ] The new commit should not have to deal with conflicts
- [ ] PR labels are created if needed and added
- [ ] One PR per service image update
- [ ] Each tag has a unique color based on the prefix. Ex: tenant/* = red, app/* = blue, env/* = green, service/* = yellow

**Comment by alambike** [comment]
@AlbertoFemenias , https://github.com/prefapp/action-deployment-dispatch/issues/21 should be moved to this repo, right? :sweat:

**Comment by AlbertoFemenias** [comment]
@alambike, I've updated this issue, I will be closing https://github.com/prefapp/action-deployment-dispatch/issues/21
